BCKND-14: Actualize README
shampiniony/dishdash-server pull request #4
Opened 2024-09-01 20:48 UTC by Vaniog

2024-09-02 06:31 UTC, AlexDyakonov commented
Not done yet

2024-09-02 06:33 UTC, AlexDyakonov commented
Sorry

2024-09-02 06:36 UTC, AlexDyakonov reviewed
Исправлен не весь ридми, доделай, пожалуйста, потом проси ревью

2024-09-02 06:36 UTC, AlexDyakonov commented on README.md
>  - Документация socket.io далее
Не изменил предыдущее

2024-09-02 06:36 UTC, AlexDyakonov commented on README.md
> -```
А тут красава, все убрал

2024-09-02 06:43 UTC, AlexDyakonov requested changes
Сделал реквест ченджес

2024-09-05 09:29 UTC, AlexDyakonov approved these changes
Все круто

2024-09-05 09:32 UTC, mikedegeofroy requested changes
Теперь вопрос такого плана... документация лучше в ГХ или в линеаре? Надо решить, тк туда сюда прыгать по докам тоже не супер)

2024-09-05 09:32 UTC, mikedegeofroy commented on README.md
> +- При `AUTO_MIGRATE=True` бек поднимет миграции при подключении, если это не удастся, он упадёт с ошибкой
Ваня, я из тебя грибной суп сделаю, я уже на это час убил))

`POSTGRES_AUTOMIGRATE=true`

2024-09-05 09:32 UTC, mikedegeofroy commented on README.md
> +
добавьте про то, где прод лежит
также было бы полезно оставить ссылки на документацию протокола

2024-09-08 12:22 UTC, mikedegeofroy approved these changes

2024-09-08 13:08 UTC, mikedegeofroy approved these changes

2024-09-08 13:10 UTC, merged